### ISSUE TITLE
Checkliste: Vor und während erstem Release

### ISSUE THREAD

**Issue by mritzmann** [dnszensur/dnszensur-web#25]
Für Release notwendig / Während Release:

- [x] repository von mritzmann/dnszensur-web zu dnszensur/dnszensur-web umziehen #21 
- [x] Webhooks testen (Deployment)
- [x] Temporäre URL entfernen und Subdomain löschen sobald PW Schutz bei api.dnszensur.ch aufgehoben wird #17
- [x] E-Mail Konversation löschen, da eventuell vertraulich #7 #8 #16 
- [x] Piwik auskommentieren
- [x] Cloudflare aktivieren
- [x] htaccess PW Schutz entfernen

Nach Release:

- [x] styleci.io kündigen #20
